'use client';

import { useState } from 'react';
import { Box, Button, Grid, Card, CardContent, Typography, MenuItem, Select, FormControl, InputLabel, IconButton } from '@mui/material';
import { Download, FileText, AlertTriangle } from 'lucide-react';
import PageContainer from '@/components/layout/PageContainer';
import PageHeader from '@/components/layout/PageHeader';
import SectionHeader from '@/components/common/SectionHeader';
import BarChart from '@/components/charts/BarChart';
import LineChart from '@/components/charts/LineChart';
import DataGrid from '@/components/tables/DataGrid';
import StatusChip from '@/components/common/StatusChip';
import FormDialog from '@/components/dialogs/FormDialog';
import { useAssets } from '@/hooks/useAssets';
import { useReports } from '@/hooks/useModules';
import { formatDate, formatCurrency } from '@/utils/format';
import type { Report } from '@/types';
import React from 'react';

export default function ReportsPage({ onMenuToggle }: { onMenuToggle?: () => void }) {
  const { data: assets = [] } = useAssets();
  const { data: reports = [], isLoading } = useReports();

  const [exportOpen, setExportOpen] = useState(false);
  const [reportType, setReportType] = useState('asset_summary');
  const [reportFormat, setReportFormat] = useState('pdf');

  // Filter assets nearing warranty or retired
  const criticalAssets = assets.filter(
    (a) => a.status === 'maintenance' || a.condition === 'poor' || a.condition === 'damaged'
  );

  // Prepare chart data: Allocation count by Department
  const deptCounts = assets.reduce((acc: Record<string, number>, curr) => {
    if (curr.status === 'allocated') {
      acc[curr.departmentName] = (acc[curr.departmentName] || 0) + 1;
    }
    return acc;
  }, {});
  const deptAllocationData = Object.entries(deptCounts).map(([name, count]) => ({
    name,
    count,
  }));

  // Prepare chart data: Asset Valuation (Line chart of purchase prices over months/years)
  const purchaseTimeData = assets
    .map((a) => ({
      date: new Date(a.purchaseDate).toLocaleDateString('en-IN', { year: 'numeric', month: 'short' }),
      price: a.purchasePrice,
    }))
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
    .slice(0, 10);

  const columns = [
    { field: 'name', headerName: 'Report Name', flex: 1.5, renderCell: (params: any) => (
      <Box sx={{ py: 0.5 }}>
        <Typography variant="body2" sx={{ fontWeight: 600, color: '#1e293b' }}>
          {params.row.name}
        </Typography>
        <Typography variant="caption" sx={{ color: '#94a3b8', fontSize: '0.65rem' }}>
          Type: {params.row.type.replace('_', ' ').toUpperCase()}
        </Typography>
      </Box>
    )},
    { field: 'generatedAt', headerName: 'Generated', flex: 1, valueGetter: (value: any, row: any) => formatDate(row.generatedAt) },
    { field: 'generatedByName', headerName: 'Generated By', flex: 1.2 },
    { field: 'fileSize', headerName: 'File Size', flex: 0.8 },
    { field: 'format', headerName: 'Format', flex: 0.8, renderCell: (params: any) => (
      <Box sx={{ display: 'inline-flex', px: 1.25, py: 0.25, borderRadius: 1, backgroundColor: '#f1f5f9', color: '#475569', fontWeight: 600 }}>
        <Typography variant="caption" sx={{ fontSize: '0.625rem' }}>{params.value.toUpperCase()}</Typography>
      </Box>
    )},
    {
      field: 'actions',
      headerName: '',
      sortable: false,
      flex: 0.8,
      align: 'right' as const,
      headerAlign: 'right' as const,
      renderCell: (params: any) => (
        <IconButton size="small" color="primary" title="Download Report">
          <Download size={16} />
        </IconButton>
      ),
    },
  ];

  const handleExportSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setExportOpen(false);
  };

  return (
    <>
      <PageHeader
        title="Reports & Analytics"
        onMenuToggle={onMenuToggle}
        actionLabel="Export Report"
        actionIcon={<Download size={16} />}
        onActionClick={() => setExportOpen(true)}
      />
      <PageContainer>
        {/* Metric Charts layout */}
        <Grid container spacing={3}>
          <Grid size={{ xs: 12, md: 6 }}>
            <BarChart
              title="Allocations by Department"
              data={deptAllocationData.length ? deptAllocationData : [{ name: 'IT', count: 8 }, { name: 'Operations', count: 12 }]}
              dataKey="count"
              xAxisKey="name"
              height={250}
            />
          </Grid>
          <Grid size={{ xs: 12, md: 6 }}>
            <LineChart
              title="Asset Purchase Trends"
              data={purchaseTimeData.length ? purchaseTimeData : [{ date: 'Jan 25', price: 150000 }, { date: 'Feb 25', price: 280000 }]}
              dataKey="price"
              xAxisKey="date"
              height={250}
            />
          </Grid>
        </Grid>

        {/* Action Registry / Critical list */}
        <Grid container spacing={3}>
          <Grid size={{ xs: 12, md: 4 }}>
            <Card sx={{ height: '100%' }}>
              <CardContent sx={{ p: '20px !important' }}>
                <SectionHeader title="Critical Asset Warning Index" />
                <Typography variant="body2" sx={{ color: '#64748b', mb: 2, fontSize: '0.75rem' }}>
                  The following assets are currently flagged for immediate attention:
                </Typography>
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
                  {criticalAssets.slice(0, 4).map((a) => (
                    <Box key={a.id} sx={{ p: 1.25, border: '1px solid #fecaca', borderRadius: 1, backgroundColor: '#fff5f5' }}>
                      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 0.5 }}>
                        <Typography variant="body2" sx={{ fontWeight: 600, color: '#b91c1c' }}>{a.assetTag}</Typography>
                        <StatusChip status={a.status} type="asset" />
                      </Box>
                      <Typography variant="body2" sx={{ color: '#7f1d1d', fontSize: '0.75rem' }}>{a.name}</Typography>
                      <Typography variant="caption" sx={{ color: '#f87171', display: 'block' }}>Reason: Condition is {a.condition}</Typography>
                    </Box>
                  ))}
                </Box>
              </CardContent>
            </Card>
          </Grid>

          <Grid size={{ xs: 12, md: 8 }}>
            <Card>
              <CardContent sx={{ p: '20px !important' }}>
                <SectionHeader title="Generated Reports History" />
                <DataGrid
                  rows={reports}
                  columns={columns}
                  loading={isLoading}
                />
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        {/* Export Dialog form */}
        <FormDialog
          open={exportOpen}
          title="Export Custom Reports Profile"
          onClose={() => setExportOpen(false)}
          onSubmit={handleExportSubmit}
          submitLabel="Generate & Download"
        >
          <FormControl fullWidth size="small">
            <InputLabel id="select-report-type">Report Focus</InputLabel>
            <Select
              labelId="select-report-type"
              value={reportType}
              label="Report Focus"
              onChange={(e) => setReportType(e.target.value)}
            >
              <MenuItem value="asset_summary">Asset Inventory Summary</MenuItem>
              <MenuItem value="allocation_history">Allocation logs history</MenuItem>
              <MenuItem value="maintenance_log">Maintenance history cost sheets</MenuItem>
              <MenuItem value="depreciation">Asset depreciation rates</MenuItem>
            </Select>
          </FormControl>

          <FormControl fullWidth size="small">
            <InputLabel id="select-report-format">File Format</InputLabel>
            <Select
              labelId="select-report-format"
              value={reportFormat}
              label="File Format"
              onChange={(e) => setReportFormat(e.target.value)}
            >
              <MenuItem value="pdf">Adobe PDF (.pdf)</MenuItem>
              <MenuItem value="xlsx">Microsoft Excel (.xlsx)</MenuItem>
              <MenuItem value="csv">Comma Separated Values (.csv)</MenuItem>
            </Select>
          </FormControl>
        </FormDialog>
      </PageContainer>
    </>
  );
}
